[3주차] 기본과제 & 심화과제
GO-SOPT-SERVER/KangSooKyung pull request #3
Opened 2023-05-02 05:37 UTC by sookyungg

📌 기본 과제

- [ ] 1. 실습코드 Github에 올리기

📌 생각 과제

- [ ] 1. 스스로 학습 키워드 정리해서 Notion에 올리기

📌 심화 과제

- [ ] 1. user테이블과 post테이블을 각각 만들고 테이블의 연관관계 만들기 (FK)

- [ ] 2. 유저 생성, 게시물 생성, 게시물 조회 구현

- [ ] 3. 각각 API에 맞는 예외 처리 구현

2023-05-04 13:33 UTC, YuSuhwa-ve requested changes
applelication.ymal 파일 꼭 내려주세요!

2023-05-04 13:33 UTC, YuSuhwa-ve commented on Week_3/week3_advanced_assignment/ThirdSeminar_advanced/ThirdSeminar/src/main/java/sopt/org/ThirdSeminar/controller/dto/response/PostResponseDto.java
> +  private UserResponseDto writer;
오 포스트 안에 유저 ResponseDto를 추가했네요. 유저정보도 같이 주게끔해서 좋은것같아요.

**P4**)  된다면 `Response interface`를 만들어 `UserResponse`, `PostResponse` 등등을 interface를 구현하는 형태로 만드는게 좋을것같아요. 그리고 이런 필드로 참조객체를 넣을때 interface로 타입을 지정하는 편이 조금더 유연한 설계가 될 수 있을것같습니다!

2023-05-04 13:33 UTC, YuSuhwa-ve commented on Week_3/week3_advanced_assignment/ThirdSeminar_advanced/ThirdSeminar/src/main/java/sopt/org/ThirdSeminar/domain/Post.java
> +  @ManyToOne(fetch = FetchType.LAZY)
P5) FetchType.LAZY를 쓴이유는 무엇인가용?

2023-05-04 13:33 UTC, YuSuhwa-ve commented on Week_3/week3_advanced_assignment/ThirdSeminar_advanced/ThirdSeminar/src/main/java/sopt/org/ThirdSeminar/domain/User.java
> +  @GeneratedValue(strategy = GenerationType.IDENTITY)
P5) 이미 찾아보셨겠지만, `GenerationType`은 여러가지가 있습니다. 이중 몇개는 `IDENTITY`와 동일한 결과를 내는데 왜 그런지 한번 찾아봐도 좋을것같습니다!

2023-05-04 13:33 UTC, YuSuhwa-ve commented on Week_3/week3_advanced_assignment/ThirdSeminar_advanced/ThirdSeminar/src/main/java/sopt/org/ThirdSeminar/common/advice/ControllerExceptionAdvice.java
> +  @ResponseStatus(HttpStatus.BAD_REQUEST)
**P4**) 같은 400번 에러라도, 다양한 이유가 있을수있으니 에러처리를 조금더 구체적으로 적는것도 좋을것같아요!

2023-05-04 13:33 UTC, YuSuhwa-ve commented on Week_3/week3_advanced_assignment/ThirdSeminar_advanced/ThirdSeminar/src/main/resources/application.yaml
> +spring:
**P1)** 지금은 로컬 아이디 비번이라 유출되어도 크게 문제는 없지만, 이런 설정정보는 매우매우매우 중요하니 `.gitignore`에 적어놓고 깃에 추적되지 않도록 하는게 중요합니다!

2023-05-04 21:50 UTC, jiyeoon00 reviewed
혹시 에러처리 구현이 너무 어려운거라면..

https://bcp0109.tistory.com/303 여기 사이트 봐바! 스프링에서 보통 어떤식으로 처리하는지 도움 받았던 사이트야!!

이번주도 수고했어~👍

2023-05-04 21:50 UTC, jiyeoon00 commented on Week_3/week3_advanced_assignment/ThirdSeminar_advanced/ThirdSeminar/src/main/java/sopt/org/ThirdSeminar/domain/User.java
> +  @GeneratedValue(strategy = GenerationType.IDENTITY)
아 나 찾아보러 가야겠다;;

2023-05-04 21:50 UTC, jiyeoon00 commented on Week_3/week3_advanced_assignment/ThirdSeminar_advanced/ThirdSeminar/src/main/java/sopt/org/ThirdSeminar/controller/dto/request/PostRequestDto.java
> +  private Long writer;
P5) 너무 사소한데, 필드 이름을 id 값이라는 걸 나타낼 수 있도록 writerId 같이 해도 좋을 것 같아!!

2023-05-05 08:40 UTC, ddongseop reviewed
양방향 연관관계 혹시 공부해보고 싶다면 아래 링크 참고해봐!
https://velog.io/@conatuseus/연관관계-매핑-기초-2-양방향-연관관계와-연관관계의-주인
그리고 양방향 연관관계에서 필드에 객체 넣을 때는 무한루프 항상 고려해야 하는데, 이 부분은 직접 해보다보면 만나게 될거야..!
심화과제까지 수고했어요~~

2023-05-05 08:40 UTC, ddongseop commented on Week_3/week3_advanced_assignment/ThirdSeminar_advanced/ThirdSeminar/src/main/java/sopt/org/ThirdSeminar/controller/dto/response/PostResponseDto.java
> +  private UserResponseDto writer;
나는 포스트 안에 유저 dto도 넣고, 유저 안에 포스트 dto의 리스트도 넣어봤거든!
이렇게 한쪽에만 response dto를 넣는 경우에는 상관이 없는데, 양쪽에 서로의 dto를 넣는 경우에는 무한루프가 발생할 여지가 있더라고!
그런 문제가 발생했을 때 수화가 말한 것처럼 interface를 사용하면 훨씬 유연하게 대처할 수 있어서, 나중에 무한루프를 만나게 된다면 적용해보면 좋을 것 같아!

2023-05-05 08:40 UTC, ddongseop commented on Week_3/week3_advanced_assignment/ThirdSeminar_advanced/ThirdSeminar/src/main/java/sopt/org/ThirdSeminar/domain/User.java
> +  @GeneratedValue(strategy = GenerationType.IDENTITY)
헉 나두....

2023-05-05 08:40 UTC, ddongseop commented on Week_3/week3_advanced_assignment/ThirdSeminar_advanced/ThirdSeminar/src/main/java/sopt/org/ThirdSeminar/exception/ErrorStatus.java
> +
P3) 게시물 조회할 때에 대한 예외처리도 해보면 좋을 것 같아요~

2023-05-05 08:40 UTC, ddongseop commented on Week_3/week3_advanced_assignment/ThirdSeminar_advanced/ThirdSeminar/src/main/java/sopt/org/ThirdSeminar/service/PostService.java
> +//    writer.addPost(post);
P5) 혹시 양방향 매핑 해보려고 했던거라면, 내 코드 참조해봐도 괜찮을 것 같아! (부족함이 많긴 하지만...)

2023-05-07 11:52 UTC, sookyungg commented on Week_3/week3_advanced_assignment/ThirdSeminar_advanced/ThirdSeminar/src/main/java/sopt/org/ThirdSeminar/controller/dto/response/PostResponseDto.java
> +  private UserResponseDto writer;
그런 여지가 발생할수도 있구나..!! 
다음부턴 그부분 고려하고 작성해야겠다

2023-06-10 16:45 UTC, merged